fix: add square button in icon button component
l3vels/l3-ui-core pull request #10
Opened 2023-01-27 09:18 UTC by DavitBakhutashvili

#### Basic
- [ ] Used plop (`npm run plop`) to create a new component.
- [ ] PR has description.
- [ ] New component is functional and uses Hooks. 
- [ ] Component defines [`PropTypes`](https://reactjs.org/docs/typechecking-with-proptypes.html).
#### Style
- [ ] Styles are added to `NewComponent.modules.scss` file inside of the `NewComponent` folder.
- [ ] Component uses CSS Modules.
- [ ] Design is compatible with [L3vels Design System](https://design.l3vels.xyz/).
#### Storybook
- [ ] Stories were added to `/src/NewComponent/__stories__/NewComponent.stories.js` file.
- [ ] Stories include all flows of using the component.
#### Tests
- [ ] Tests are compliant with [TESTING_README.md](TESTING_README.md) instructions.

2023-01-27 09:41 UTC, jemiks requested changes

2023-01-27 09:41 UTC, jemiks commented on src/components/IconButton/IconButton.tsx
> +        {shape === "Circle" ? (
remove this check

2023-01-27 09:47 UTC, DavitBakhutashvili commented on src/components/IconButton/IconButton.tsx
> +        {shape === "Circle" ? (
ok

2023-01-30 11:05 UTC, jemiks requested changes

2023-01-30 19:21 UTC, jemiks approved these changes

2023-01-30 19:22 UTC, merged