Feat/textarea
l3vels/l3-ui-core pull request #25
Opened 2023-02-07 11:50 UTC by levanion

#### Basic
- [ ] Used plop (`npm run plop`) to create a new component.
- [ ] PR has description.
- [ ] New component is functional and uses Hooks. 
- [ ] Component defines [`PropTypes`](https://reactjs.org/docs/typechecking-with-proptypes.html).
#### Style
- [ ] Styles are added to `NewComponent.modules.scss` file inside of the `NewComponent` folder.
- [ ] Component uses CSS Modules.
- [ ] Design is compatible with [L3vels Design System](https://design.l3vels.xyz/).
#### Storybook
- [ ] Stories were added to `/src/NewComponent/__stories__/NewComponent.stories.js` file.
- [ ] Stories include all flows of using the component.
#### Tests
- [ ] Tests are compliant with [TESTING_README.md](TESTING_README.md) instructions.

2023-02-07 11:52 UTC, levanion commented
https://www.notion.so/expected/Textarea-9990c7fa79304df3abfba1ae36caabb7

2023-02-07 11:56 UTC, levanion commented
https://www.notion.so/expected/Textarea-9990c7fa79304df3abfba1ae36caabb7

2023-02-07 15:26 UTC, jemiks requested changes

2023-02-07 15:26 UTC, jemiks commented on src/components/Textarea/Textarea.module.scss
> +  font-style: normal;
import this styles from typography

2023-02-07 15:26 UTC, jemiks commented on src/components/Textarea/Textarea.tsx
> +          onSelect={onSelect}
please check the props some of these props is not relevant to the textarea,  for example, select is not the correct prop for it,
this more details here 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

2023-02-08 13:51 UTC, jemiks requested changes

2023-02-08 16:53 UTC, jemiks approved these changes

2023-02-08 16:53 UTC, merged